version: '3.7'
services:
  redis:
    image: redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"

  api:
    build: .
    depends_on:
      - redis
    restart: always
    volumes:
      - type: bind
        source: ./config.yml
        target: /config.yml
    ports:
      - "8080:8080"